import { createHash, randomBytes, randomUUID } from "node:crypto";
import { createServer } from "node:http";
import { Pool } from "pg";

const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : undefined });
const port = Number(process.env.PORT ?? 3000);
const json = (res: import("node:http").ServerResponse, status: number, body: unknown) => { res.writeHead(status, { "content-type": "application/json", "cache-control": "no-store" }); res.end(JSON.stringify(body)); };
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const token = () => randomBytes(32).toString("hex");

async function migrate() {
  await pool.query(`CREATE TABLE IF NOT EXISTS social_accounts (
    id UUID PRIMARY KEY, handle TEXT UNIQUE NOT NULL CHECK (handle ~ '^[a-z0-9_]{3,24}$'), display_name TEXT NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 60), token_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS social_presence (account_id UUID PRIMARY KEY REFERENCES social_accounts(id) ON DELETE CASCADE, state TEXT NOT NULL CHECK (state IN ('working','idle')), last_seen_at TIMESTAMPTZ NOT NULL, active_sessions INTEGER NOT NULL DEFAULT 0 CHECK (active_sessions >= 0));
    CREATE TABLE IF NOT EXISTS social_metrics (account_id UUID PRIMARY KEY REFERENCES social_accounts(id) ON DELETE CASCADE, visibility TEXT NOT NULL DEFAULT 'friends' CHECK (visibility IN ('private','friends','public')), tokens_today BIGINT NOT NULL DEFAULT 0, tokens_week BIGINT NOT NULL DEFAULT 0, focus_minutes_week INTEGER NOT NULL DEFAULT 0, streak_days INTEGER NOT NULL DEFAULT 0, calendar JSONB NOT NULL DEFAULT '[]', observed_at TIMESTAMPTZ NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS friendships (requester_id UUID REFERENCES social_accounts(id) ON DELETE CASCADE, recipient_id UUID REFERENCES social_accounts(id) ON DELETE CASCADE, status TEXT NOT NULL CHECK (status IN ('pending','accepted','declined')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), decided_at TIMESTAMPTZ, PRIMARY KEY (requester_id, recipient_id), CHECK (requester_id <> recipient_id));
    CREATE INDEX IF NOT EXISTS friendships_recipient_pending ON friendships(recipient_id, status);
    CREATE TABLE IF NOT EXISTS social_activity (id BIGSERIAL PRIMARY KEY, account_id UUID REFERENCES social_accounts(id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK (kind IN ('started','updatedMetrics')), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
    CREATE INDEX IF NOT EXISTS social_activity_account_time ON social_activity(account_id, created_at DESC);`);
}
async function body(req: import("node:http").IncomingMessage) { let raw=""; for await (const chunk of req) { raw += chunk; if (raw.length > 32_768) throw Error("tooLarge"); } return raw ? JSON.parse(raw) as Record<string, unknown> : {}; }
async function me(req: import("node:http").IncomingMessage) { const raw = req.headers.authorization?.replace(/^Bearer\s+/i, ""); if (!raw) return null; const row = await pool.query("SELECT id, handle, display_name FROM social_accounts WHERE token_hash = $1", [hash(raw)]); return row.rows[0] as {id:string;handle:string;display_name:string}|undefined; }
function profile(row: Record<string, unknown>) { const seen=row.last_seen_at?new Date(String(row.last_seen_at)).getTime():0; const fresh=seen>0&&Date.now()-seen<120_000; return { id: row.id, handle: row.handle, displayName: row.display_name, presence: fresh ? { state: row.state, lastSeenAt: row.last_seen_at, activeSessions: row.active_sessions } : (row.last_seen_at ? { state: "idle", lastSeenAt: row.last_seen_at, activeSessions: 0 } : null), metrics: !row.visibility || row.visibility === "private" ? null : { visibility: row.visibility, tokensToday: row.tokens_today, tokensWeek: row.tokens_week, focusMinutesWeek: row.focus_minutes_week, streakDays: row.streak_days, calendar: row.calendar, observedAt: row.observed_at } }; }

await migrate();
createServer(async (req, res) => { try {
  const url = new URL(req.url ?? "/", `http://${req.headers.host}`);
  if (req.method === "GET" && url.pathname === "/health") return json(res, 200, { ok: true });
  if (req.method === "POST" && url.pathname === "/v1/accounts") { const b=await body(req); const handle=typeof b.handle==="string"?b.handle.trim().toLowerCase():""; const displayName=typeof b.displayName==="string"?b.displayName.trim():""; if(!/^[a-z0-9_]{3,24}$/.test(handle)||!displayName||displayName.length>60)return json(res,400,{error:"social.invalidProfile"}); const id=randomUUID(), secret=token(); try { await pool.query("INSERT INTO social_accounts(id,handle,display_name,token_hash) VALUES($1,$2,$3,$4)",[id,handle,displayName,hash(secret)]); return json(res,201,{account:{id,handle,displayName},token:secret}); } catch { return json(res,409,{error:"social.handleTaken"}); } }
  const account=await me(req); if(!account)return json(res,401,{error:"social.unauthorised"});
  if(req.method==="POST"&&url.pathname==="/v1/heartbeat"){const b=await body(req), active=Number(b.activeSessions); if(!Number.isInteger(active)||active<0||active>100)return json(res,400,{error:"social.invalidPresence"}); await pool.query("INSERT INTO social_presence(account_id,state,last_seen_at,active_sessions) VALUES($1,$2,now(),$3) ON CONFLICT(account_id) DO UPDATE SET state=excluded.state,last_seen_at=excluded.last_seen_at,active_sessions=excluded.active_sessions",[account.id,active>0?"working":"idle",active]); return json(res,200,{ok:true});}
  if(req.method==="GET"&&url.pathname==="/v1/me") { const result=await pool.query("SELECT a.id,a.handle,a.display_name,p.state,p.last_seen_at,p.active_sessions,m.* FROM social_accounts a LEFT JOIN social_presence p ON p.account_id=a.id LEFT JOIN social_metrics m ON m.account_id=a.id WHERE a.id=$1",[account.id]); return json(res,200,{profile:profile(result.rows[0])}); }
  if(req.method==="POST"&&url.pathname==="/v1/metrics") { const b=await body(req), visibility=String(b.visibility); const numbers=[b.tokensToday,b.tokensWeek,b.focusMinutesWeek,b.streakDays].map(Number); if(!["private","friends","public"].includes(visibility)||numbers.some(n=>!Number.isInteger(n)||n<0))return json(res,400,{error:"social.invalidMetrics"}); const calendar=Array.isArray(b.calendar)?b.calendar.slice(-91):[]; await pool.query("INSERT INTO social_metrics(account_id,visibility,tokens_today,tokens_week,focus_minutes_week,streak_days,calendar,observed_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()) ON CONFLICT(account_id) DO UPDATE SET visibility=excluded.visibility,tokens_today=excluded.tokens_today,tokens_week=excluded.tokens_week,focus_minutes_week=excluded.focus_minutes_week,streak_days=excluded.streak_days,calendar=excluded.calendar,observed_at=excluded.observed_at",[account.id,visibility,...numbers,JSON.stringify(calendar)]); await pool.query("INSERT INTO social_activity(account_id,kind) VALUES($1,'updatedMetrics')",[account.id]); return json(res,200,{ok:true}); }
  if(req.method==="POST"&&url.pathname.startsWith("/v1/friends/")) { const handle=url.pathname.slice("/v1/friends/".length).toLowerCase(); const target=(await pool.query("SELECT id,handle,display_name FROM social_accounts WHERE handle=$1",[handle])).rows[0]; if(!target||target.id===account.id)return json(res,404,{error:"social.profileNotFound"}); const old=(await pool.query("SELECT * FROM friendships WHERE (requester_id=$1 AND recipient_id=$2) OR (requester_id=$2 AND recipient_id=$1)",[account.id,target.id])).rows[0]; if(old?.status==="accepted")return json(res,200,{status:"accepted"}); if(old?.requester_id===target.id&&old.status==="pending"){await pool.query("UPDATE friendships SET status='accepted',decided_at=now() WHERE requester_id=$1 AND recipient_id=$2",[target.id,account.id]); return json(res,200,{status:"accepted"});} if(!old)await pool.query("INSERT INTO friendships(requester_id,recipient_id,status) VALUES($1,$2,'pending')",[account.id,target.id]); return json(res,201,{status:"pending"}); }
  if(req.method==="POST"&&url.pathname.startsWith("/v1/friend-requests/")&&url.pathname.endsWith("/accept")) { const requester=url.pathname.slice(20,-7); const changed=await pool.query("UPDATE friendships SET status='accepted',decided_at=now() WHERE requester_id=$1 AND recipient_id=$2 AND status='pending'",[requester,account.id]); return changed.rowCount?json(res,200,{status:"accepted"}):json(res,404,{error:"social.requestNotFound"}); }
  if(req.method==="GET"&&url.pathname==="/v1/friends") { const result=await pool.query("SELECT a.id,a.handle,a.display_name,p.state,p.last_seen_at,p.active_sessions,m.visibility,m.tokens_today,m.tokens_week,m.focus_minutes_week,m.streak_days,m.calendar,m.observed_at,f.status, f.requester_id FROM friendships f JOIN social_accounts a ON a.id=CASE WHEN f.requester_id=$1 THEN f.recipient_id ELSE f.requester_id END LEFT JOIN social_presence p ON p.account_id=a.id LEFT JOIN social_metrics m ON m.account_id=a.id WHERE f.requester_id=$1 OR f.recipient_id=$1 ORDER BY COALESCE(p.last_seen_at,a.updated_at) DESC",[account.id]); return json(res,200,{friends:result.rows.filter(row=>row.status==='accepted').map(profile),requests:result.rows.filter(row=>row.status==='pending'&&row.requester_id!==account.id).map(profile)}); }
  if(req.method==="GET"&&url.pathname.startsWith("/v1/profiles/")) { const handle=url.pathname.slice(13).toLowerCase(); const row=(await pool.query("SELECT a.id,a.handle,a.display_name,p.state,p.last_seen_at,p.active_sessions,m.* FROM social_accounts a LEFT JOIN social_presence p ON p.account_id=a.id LEFT JOIN social_metrics m ON m.account_id=a.id WHERE a.handle=$1",[handle])).rows[0]; if(!row)return json(res,404,{error:"social.profileNotFound"}); const linked=((await pool.query("SELECT status FROM friendships WHERE status='accepted' AND ((requester_id=$1 AND recipient_id=$2) OR (requester_id=$2 AND recipient_id=$1))",[account.id,row.id])).rowCount ?? 0)>0; if(row.visibility==='private'||(row.visibility==='friends'&&!linked))row.visibility='private'; return json(res,200,{profile:profile(row),friend:linked}); }
  return json(res,404,{error:"social.notFound"});
} catch (error) { console.error(error); json(res,500,{error:"social.internal"}); } }).listen(port, () => console.log(`social api on ${port}`));
